services:
  pb-server:
    build:
      context: ../..
      dockerfile: etc/docker/Dockerfile
    environment:
      PB_SERVER_PORT: "8000"
      PB_SERVER_HOST: "0.0.0.0"
    expose:
      - "8000"
    networks:
      - pb-net

networks:
  pb-net: {}
